#!/usr/bin/env python3
"""Build the public site into `site/dist/`.

    python3 site/build.py

Produces three things and nothing else:

  index.html    the landing page, with style.css inlined
  demo/         the real dashboard, rendered from the deterministic demo fixture
  _headers      Cloudflare Pages security headers

The demo is the load-bearing part. Every tool in this category has the same
onboarding problem — the dashboard is the pitch and you cannot see it without
weeks of your own data — so the site ships the actual artefact, generated by the
same code path a user runs locally. Not a screenshot, which goes stale silently.

Stdlib only, like the engine. A site build that needs npm would be the first
dependency in the repo and it would be for a landing page.
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
ENGINE = ROOT / "observatory"
OUT = HERE / "dist"

# Cloudflare Pages reads this file. The dashboard and this page both promise
# zero external requests; the CSP is what makes that promise enforceable by the
# browser rather than a claim in a README.
HEADERS = """/*
  X-Frame-Options: DENY
  X-Content-Type-Options: nosniff
  Referrer-Policy: no-referrer
  Permissions-Policy: geolocation=(), microphone=(), camera=(), interest-cohort=()
  Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src 'self' data:; form-action 'none'; frame-ancestors 'none'; base-uri 'none'
"""


def build_demo() -> str:
    """Render the dashboard from the demo fixture, in a scratch data dir."""
    sys.path.insert(0, str(ENGINE))
    import analyze, demo, insights, normalize, pricing, render  # noqa: E402

    data = OUT / ".scratch"
    if data.exists():
        shutil.rmtree(data)
    data.mkdir(parents=True)

    normalize.write_events(data, demo.generate())
    prices = pricing.load_pricing()
    digest = analyze.build_digest(normalize.read_events(data), prices)
    digest["findings"] = insights.generate(digest, prices)
    # The published demo is deliberately USD/UTC+8 with no plan configured, so
    # it shows the shape of the product rather than one person's settings.
    digest["settings"] = {
        "tz_offset_hours": 8, "tz_label": "UTC+8", "currency": "USD",
        "symbol": "$", "per_usd": 1, "decimals": 2, "plan": "none",
    }
    html = render.render(digest)
    shutil.rmtree(data)
    return html


def main() -> int:
    if OUT.exists():
        shutil.rmtree(OUT)
    (OUT / "demo").mkdir(parents=True)

    css = (HERE / "style.css").read_text(encoding="utf-8")
    page = (HERE / "index.html").read_text(encoding="utf-8")
    if "/*CSS*/" not in page:
        print("build: index.html has no /*CSS*/ placeholder", file=sys.stderr)
        return 1
    (OUT / "index.html").write_text(page.replace("/*CSS*/", css), encoding="utf-8")

    (OUT / "demo" / "index.html").write_text(build_demo(), encoding="utf-8")
    (OUT / "_headers").write_text(HEADERS, encoding="utf-8")

    for path in sorted(OUT.rglob("*")):
        if path.is_file():
            print(f"  {path.relative_to(OUT)}  {path.stat().st_size / 1024:.0f} KB")
    print(f"site: built into {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
