#!/usr/bin/env python3
"""Build the public site into `site/dist/`.

    python3 site/build.py

Produces:

  index.html          the landing page in English
  <lang>/index.html   the same page in twelve more languages
  demo/               the real dashboard, from the deterministic demo fixture
  sitemap.xml         every locale, cross-linked
  robots.txt
  _headers            Cloudflare Pages security headers

The demo is the load-bearing part. Every tool in this category has the same
onboarding problem — the dashboard is the pitch and you cannot see it without
weeks of your own data — so the site ships the actual artefact, generated by the
same code path a user runs locally. Not a screenshot, which goes stale silently.

One page per language rather than a client-side switcher: each locale gets a
crawlable URL, an `hreflang` set, and works with scripting off. The dashboard
takes the opposite route (one page, switched in the browser) because it is also
opened from `file://` on people's laptops, where there is no directory of
alternates to link to. Both read the same `observatory-lang` key, so a choice
made on the landing page carries into the demo.

Stdlib only, like the engine. A site build that needs npm would be the first
dependency in the repo and it would be for a landing page.
"""

from __future__ import annotations

import html
import os
import re
import shutil
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
ENGINE = ROOT / "observatory"
OUT = HERE / "dist"

sys.path.insert(0, str(HERE))
import i18n  # noqa: E402

# Absolute URLs are required in hreflang and sitemap entries. The default is the
# project's own deploy; a fork overrides it rather than editing this file.
SITE = os.environ.get("SITE_URL", "https://ai-observatory.workers.dev").rstrip("/")
REPO = "https://github.com/jxxyx-bloop/ai-observatory"

# Cloudflare Pages reads this file. The dashboard and this page both promise
# zero external requests; the CSP is what makes that promise enforceable by the
# browser rather than a claim in a README.
HEADERS = """/*
  X-Frame-Options: DENY
  X-Content-Type-Options: nosniff
  Referrer-Policy: no-referrer
  Permissions-Policy: geolocation=(), microphone=(), camera=(), interest-cohort=()
  Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src 'self' data:; form-action 'none'; frame-ancestors 'none'; base-uri 'none'
"""

ROBOTS = f"""User-agent: *
Allow: /
Sitemap: {SITE}/sitemap.xml
"""


def esc(v: str) -> str:
    return html.escape(str(v), quote=True)


# ── Landing page ─────────────────────────────────────────────────────────────

def finding_cards(t: dict) -> str:
    """The three sample findings, in the reader's language.

    Hard-coded rather than pulled from the demo digest: these are the pitch, and
    the pitch has to be translated. The demo dashboard one click away carries
    the real, generated ones.
    """
    rows = [("f1", "high"), ("f2", "med"), ("f3", "low")]
    out = []
    for key, sev in rows:
        out.append(
            f'<article class="find" style="--sev:var(--{sev})">'
            f'<div class="top">'
            f'<span class="sev">{esc(t["sev_" + sev])}</span>'
            f'<span class="ttl">{esc(t[key + "_title"])}</span>'
            f'<span class="save">{esc(t[key + "_save"])}</span>'
            f'</div>'
            f'<p class="body">{esc(t[key + "_body"])}</p>'
            f'<p class="act">{esc(t[key + "_act"])}</p>'
            f'</article>'
        )
    return "\n    ".join(out)


def lang_links(current: str) -> str:
    """The switcher menu. Native name first, English name greyed beside it, so
    someone who landed on the wrong language can still find their way out."""
    out = []
    for code, d, native, _short, _hl in i18n.LOCALES:
        # From inside a locale directory every sibling is one level up.
        href = ("../" if current != "en" else "") + (f"{d}/" if d else "./")
        cur = ' aria-current="true"' if code == current else ""
        out.append(
            f'<a href="{href}" data-lang="{esc(code)}" hreflang="{esc(code)}"'
            f' lang="{esc(code)}"{cur}>{esc(native)}'
            f'<span class="en">{esc(i18n.ENGLISH_NAME[code])}</span></a>'
        )
    return "\n      ".join(out)


def alternates(current: str) -> str:
    out = []
    for code, d, *_ in i18n.LOCALES:
        url = f"{SITE}/{d}/" if d else f"{SITE}/"
        out.append(f'<link rel="alternate" hreflang="{esc(code)}" href="{esc(url)}">')
    out.append(f'<link rel="alternate" hreflang="x-default" href="{esc(SITE)}/">')
    cur = next(d for c, d, *_ in i18n.LOCALES if c == current)
    url = f"{SITE}/{cur}/" if cur else f"{SITE}/"
    out.append(f'<link rel="canonical" href="{esc(url)}">')
    return "\n".join(out)


def render_landing(code: str, template: str, css: str, js: str) -> str:
    t = i18n.strings(code)
    meta = dict((c, (d, native, short, hl))
                for c, d, native, short, hl in i18n.LOCALES)
    _dir, _native, short, htmllang = meta[code]

    page = template.replace("/*CSS*/", css).replace("/*JS*/", js)
    fields = {
        "htmllang": htmllang,
        "lang_code": short,
        "langlinks": lang_links(code),
        "alternates": alternates(code),
        "findings": finding_cards(t),
        "repo": REPO,
        # English is the site root; every other locale sits one directory down.
        "base": "" if code == "en" else "../",
        "home": "./" if code == "en" else "../",
    }
    for key, value in t.items():
        fields.setdefault(key, esc(value))
    for key, value in fields.items():
        page = page.replace("{{" + key + "}}", str(value))

    if "{{" in page:
        start = page.index("{{")
        raise SystemExit(f"build: unresolved placeholder near {page[start:start + 40]!r}")
    return page


# ── Demo dashboard ───────────────────────────────────────────────────────────

def build_demo() -> str:
    """Render the dashboard from the demo fixture, in a scratch data dir."""
    sys.path.insert(0, str(ENGINE))
    import analyze, demo, insights, normalize, pricing, render  # noqa: E402

    data = OUT / ".scratch"
    if data.exists():
        shutil.rmtree(data)
    data.mkdir(parents=True)

    normalize.write_events(data, demo.generate())
    prices = pricing.load_pricing()
    digest = analyze.build_digest(normalize.read_events(data), prices)
    digest["findings"] = insights.generate(digest, prices)
    # The published demo is deliberately USD/UTC+8 with no plan configured, so
    # it shows the shape of the product rather than one person's settings.
    digest["settings"] = {
        "tz_offset_hours": 8, "tz_label": "UTC+8", "currency": "USD",
        "symbol": "$", "per_usd": 1, "decimals": 2, "plan": "none",
    }
    # `home` is what puts a breadcrumb back to the landing page on the hosted
    # copy. A locally rendered dashboard passes nothing and links to the repo
    # instead, because there is no site to go back to.
    html_out = render.render(digest, home="../")
    shutil.rmtree(data)
    return html_out


def check_locale_tables() -> None:
    """The landing page and the dashboard keep separate locale tables.

    They have to: one is Python that runs at build time, the other is JavaScript
    that runs in a browser opened from `file://`. But two lists that can
    disagree eventually will — a locale added to one and not the other gives a
    switcher entry that 404s, and only a reader who needs that language would
    ever find it. So they are compared here, on every build.
    """
    js = (ENGINE / "assets" / "i18n.js").read_text(encoding="utf-8")
    block = js[js.index("var LOCALES = ["):js.index("];", js.index("var LOCALES = ["))]
    found = re.findall(r'\[\s*"([^"]*)"\s*,\s*"[^"]*"\s*,\s*"[^"]*"\s*,\s*"([^"]*)"\s*\]',
                       block)
    want = [(code, d) for code, d, *_ in i18n.LOCALES]
    if found != want:
        raise SystemExit(
            "build: site/i18n.py and observatory/assets/i18n.js disagree about "
            f"locales.\n  python: {want}\n  js:     {found}")


def sitemap() -> str:
    rows = []
    for _code, d, *_ in i18n.LOCALES:
        rows.append(f"  <url><loc>{SITE}/{d}/</loc></url>" if d
                    else f"  <url><loc>{SITE}/</loc></url>")
    rows.append(f"  <url><loc>{SITE}/demo/</loc></url>")
    body = "\n".join(rows)
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
            f"{body}\n</urlset>\n")


def main() -> int:
    if OUT.exists():
        shutil.rmtree(OUT)
    (OUT / "demo").mkdir(parents=True)

    check_locale_tables()

    template = (HERE / "index.html").read_text(encoding="utf-8")
    js = (HERE / "app.js").read_text(encoding="utf-8")
    # Tokens first, then layout — the same order every surface uses, so the
    # landing page and the dashboard cannot drift apart.
    css = ((ENGINE / "assets" / "tokens.css").read_text(encoding="utf-8")
           + "\n" + (HERE / "style.css").read_text(encoding="utf-8"))

    if "/*CSS*/" not in template or "/*JS*/" not in template:
        print("build: index.html is missing a /*CSS*/ or /*JS*/ placeholder",
              file=sys.stderr)
        return 1

    for code, d, *_ in i18n.LOCALES:
        page = render_landing(code, template, css, js)
        target = OUT / d / "index.html" if d else OUT / "index.html"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(page, encoding="utf-8")

    (OUT / "demo" / "index.html").write_text(build_demo(), encoding="utf-8")
    (OUT / "_headers").write_text(HEADERS, encoding="utf-8")
    (OUT / "robots.txt").write_text(ROBOTS, encoding="utf-8")
    (OUT / "sitemap.xml").write_text(sitemap(), encoding="utf-8")

    gaps = i18n.missing()
    if gaps:
        # Not a failure. A locale with a few English lines still beats no locale,
        # and naming them here is what turns "someday" into a reviewable diff.
        print("site: falling back to English for some keys —")
        for code, keys in gaps.items():
            print(f"  {code}: {', '.join(keys)}")

    total = 0
    for path in sorted(OUT.rglob("*")):
        if path.is_file():
            size = path.stat().st_size
            total += size
            print(f"  {path.relative_to(OUT)}  {size / 1024:.0f} KB")
    print(f"site: {len(i18n.LOCALES)} locales, {total / 1024:.0f} KB into "
          f"{OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
