#!/usr/bin/env python3
"""Build the public site into `site/dist/`.

    python3 site/build.py

Produces:

  index.html          the landing page in English
  <lang>/index.html   the same page in twelve more languages
  demo/               the real dashboard, from the deterministic demo fixture
  sitemap.xml         every locale, cross-linked
  robots.txt
  _headers            Cloudflare Pages security headers

The demo is the load-bearing part. Every tool in this category has the same
onboarding problem — the dashboard is the pitch and you cannot see it without
weeks of your own data — so the site ships the actual artefact, generated by the
same code path a user runs locally. Not a screenshot, which goes stale silently.

One page per language rather than a client-side switcher: each locale gets a
crawlable URL, an `hreflang` set, and works with scripting off. The dashboard
takes the opposite route (one page, switched in the browser) because it is also
opened from `file://` on people's laptops, where there is no directory of
alternates to link to. Both read the same `observatory-lang` key, so a choice
made on the landing page carries into the demo.

Stdlib only, like the engine. A site build that needs npm would be the first
dependency in the repo and it would be for a landing page.
"""

from __future__ import annotations

import base64
import hashlib
import html
import os
import re
import shutil
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
ENGINE = ROOT / "observatory"
OUT = HERE / "dist"

sys.path.insert(0, str(HERE))
import i18n  # noqa: E402

# Absolute URLs are required in hreflang and sitemap entries. The default is the
# project's own deploy; a fork overrides it rather than editing this file.
#
# This must stay equal to the host that actually serves the site. It had drifted
# to a shorter name that resolves nowhere, which put a canonical link, an
# hreflang set and a whole sitemap on every page pointing at a domain this
# project does not own — telling search engines the real home of this content is
# somewhere else, and leaving that somewhere else for anyone to register.
# The canonical host. It ends up in the sitemap, in every `hreflang` alternate
# and in the demo's own links, so it has to be the name people should land on
# rather than whichever hostname happens to answer — the site is also reachable
# at its workers.dev address, and two hosts serving one page is a duplicate in
# every index that reads this file. `SITE_URL` overrides it for a fork.
SITE = os.environ.get("SITE_URL", "https://aiobservatory.dev").rstrip("/")
REPO = "https://github.com/jxxyx-bloop/ai-observatory"

# Cloudflare Pages reads this file. The dashboard and this page both promise
# zero external requests; the CSP is what makes that promise enforceable by the
# browser rather than a claim in a README.
#
# script-src carries SHA-256 hashes rather than 'unsafe-inline', and that is the
# point of this whole block. With 'unsafe-inline' any HTML that reached a page —
# through a build bug, a bad translation string, a future template — would
# execute. With hashes, only the exact scripts this build produced can run, and
# injected markup is inert. The hashes are computed from the emitted files by
# `inline_script_hashes` below, never written by hand: a hardcoded hash is one
# refactor away from a blank page, and a CSP nobody can safely edit gets deleted.
#
# style-src keeps 'unsafe-inline' deliberately. Hashes cover <style> elements
# but not style="" attributes, which both the landing page and the dashboard use
# for data-driven widths and colours; adding a style hash would make the browser
# ignore 'unsafe-inline' and silently strip that styling. Inline CSS also cannot
# execute script, so this is a much smaller surface than the one above.
#
# includeSubDomains is free of consequence on *.workers.dev: production is
# ai-observatory.jiayilee.workers.dev and previews are
# <branch>-ai-observatory.jiayilee.workers.dev, which are siblings rather than
# subdomains, so the directive covers this host and nothing else. A custom apex
# domain would change that — it would pin every subdomain of that apex to HTTPS
# for a year, so any plain-HTTP sibling has to be found before such a move, not
# after. No preload: joining the browsers' preload list is effectively
# irreversible and is not ours to opt into silently.
#
# No Cache-Control: every page here is public, static and identical for every
# reader. `no-store` belongs on authenticated or personal content, and there is
# none — the dashboard with real data is rendered on the reader's own machine
# and never travels through this host.
PERMISSIONS = ", ".join(f"{feature}=()" for feature in (
    "accelerometer", "autoplay", "browsing-topics", "camera", "display-capture",
    "encrypted-media", "geolocation", "gyroscope", "idle-detection",
    "interest-cohort", "magnetometer", "microphone", "midi", "payment",
    "publickey-credentials-get", "screen-wake-lock", "serial", "usb",
    "xr-spatial-tracking",
))

# Inline <script> bodies, minus any that loads a src — those cannot exist here
# (site/tools/check_no_remote.py fails the build on a remote subresource) but
# matching on the attribute keeps this correct if that ever changes.
SCRIPT_TAG = re.compile(r"<script(?![^>]*\bsrc\s*=)([^>]*)>(.*?)</script>",
                        re.I | re.S)


def inline_script_hashes(root: Path) -> list[str]:
    """Every inline script the build emitted, as CSP source expressions.

    The browser hashes the exact text between the tags, so this must too — no
    stripping, no normalising. Sorted and de-duplicated because the head theme
    stamp and the shared app bundle are byte-identical across all thirteen
    locales, and thirteen copies of one hash would be thirteen chances to
    disagree.
    """
    found = set()
    for page in sorted(root.rglob("*.html")):
        for _attrs, body in SCRIPT_TAG.findall(page.read_text(encoding="utf-8")):
            digest = hashlib.sha256(body.encode("utf-8")).digest()
            found.add("'sha256-" + base64.b64encode(digest).decode("ascii") + "'")
    if not found:
        raise SystemExit("build: no inline scripts found — refusing to write a "
                         "CSP that would allow nothing and break every page")
    return sorted(found)


def headers_file(script_hashes: list[str]) -> str:
    csp = "; ".join((
        "default-src 'none'",
        "script-src " + " ".join(script_hashes),
        "style-src 'unsafe-inline'",
        "img-src 'self' data:",
        "form-action 'none'",
        "frame-ancestors 'none'",
        "base-uri 'none'",
    ))
    return "\n".join((
        "/*",
        "  Strict-Transport-Security: max-age=31536000; includeSubDomains",
        "  X-Frame-Options: DENY",
        "  X-Content-Type-Options: nosniff",
        "  Referrer-Policy: no-referrer",
        "  Cross-Origin-Opener-Policy: same-origin",
        "  Cross-Origin-Resource-Policy: same-origin",
        "  X-Permitted-Cross-Domain-Policies: none",
        f"  Permissions-Policy: {PERMISSIONS}",
        f"  Content-Security-Policy: {csp}",
        "",
    ))


ROBOTS = f"""User-agent: *
Allow: /
Sitemap: {SITE}/sitemap.xml
"""


def esc(v: str) -> str:
    return html.escape(str(v), quote=True)


# ── Landing page ─────────────────────────────────────────────────────────────

def finding_cards(t: dict) -> str:
    """The three sample findings, in the reader's language.

    Hard-coded rather than pulled from the demo digest: these are the pitch, and
    the pitch has to be translated. The demo dashboard one click away carries
    the real, generated ones.
    """
    rows = [("f1", "high"), ("f2", "med"), ("f3", "low")]
    out = []
    for key, sev in rows:
        out.append(
            f'<article class="find" style="--sev:var(--{sev})">'
            f'<div class="top">'
            f'<span class="sev">{esc(t["sev_" + sev])}</span>'
            f'<span class="ttl">{esc(t[key + "_title"])}</span>'
            f'<span class="save">{esc(t[key + "_save"])}</span>'
            f'</div>'
            f'<p class="body">{esc(t[key + "_body"])}</p>'
            f'<p class="act">{esc(t[key + "_act"])}</p>'
            f'</article>'
        )
    return "\n    ".join(out)


def lang_links(current: str) -> str:
    """The switcher menu. Native name first, English name greyed beside it, so
    someone who landed on the wrong language can still find their way out."""
    out = []
    for code, d, native, _short, _hl in i18n.LOCALES:
        # From inside a locale directory every sibling is one level up.
        href = ("../" if current != "en" else "") + (f"{d}/" if d else "./")
        cur = ' aria-current="true"' if code == current else ""
        out.append(
            f'<a href="{href}" data-lang="{esc(code)}" hreflang="{esc(code)}"'
            f' lang="{esc(code)}"{cur}>{esc(native)}'
            f'<span class="en">{esc(i18n.ENGLISH_NAME[code])}</span></a>'
        )
    return "\n      ".join(out)


def alternates(current: str) -> str:
    out = []
    for code, d, *_ in i18n.LOCALES:
        url = f"{SITE}/{d}/" if d else f"{SITE}/"
        out.append(f'<link rel="alternate" hreflang="{esc(code)}" href="{esc(url)}">')
    out.append(f'<link rel="alternate" hreflang="x-default" href="{esc(SITE)}/">')
    cur = next(d for c, d, *_ in i18n.LOCALES if c == current)
    url = f"{SITE}/{cur}/" if cur else f"{SITE}/"
    out.append(f'<link rel="canonical" href="{esc(url)}">')
    return "\n".join(out)


def render_landing(code: str, template: str, css: str, js: str) -> str:
    t = i18n.strings(code)
    meta = dict((c, (d, native, short, hl))
                for c, d, native, short, hl in i18n.LOCALES)
    _dir, _native, short, htmllang = meta[code]

    page = template.replace("/*CSS*/", css).replace("/*JS*/", js)
    fields = {
        "htmllang": htmllang,
        "lang_code": short,
        "langlinks": lang_links(code),
        "alternates": alternates(code),
        "findings": finding_cards(t),
        "repo": REPO,
        # English is the site root; every other locale sits one directory down.
        "base": "" if code == "en" else "../",
        "home": "./" if code == "en" else "../",
    }
    for key, value in t.items():
        fields.setdefault(key, esc(value))
    for key, value in fields.items():
        page = page.replace("{{" + key + "}}", str(value))

    if "{{" in page:
        start = page.index("{{")
        raise SystemExit(f"build: unresolved placeholder near {page[start:start + 40]!r}")
    return page


def render_setup(template: str, css: str, js: str, setup_js: str) -> str:
    """The setup walkthrough, in English only — deliberately.

    Every other page here ships in thirteen languages. This one does not, and
    the reason is the same one `site/tools/readmes.py` gives for leaving the
    command table out of the translated READMEs: it is a dense procedural page
    of shell commands, flags and file paths, where **a stale translation of a
    command is worse than an English one**. A mistranslated heading costs a
    reader a moment; a mistranslated command costs them the install.

    The chrome still resolves through the same placeholders as the landing
    page, so the header, footer and theme cannot drift.
    """
    page = (template.replace("/*CSS*/", css)
                    .replace("/*SETUPJS*/", setup_js)
                    .replace("/*JS*/", js))
    for key, value in {"repo": REPO, "site": SITE, "base": "../"}.items():
        page = page.replace("{{" + key + "}}", str(value))
    if "{{" in page:
        start = page.index("{{")
        raise SystemExit(f"build: unresolved placeholder in setup.html near "
                         f"{page[start:start + 40]!r}")
    return page


# ── Demo dashboard ───────────────────────────────────────────────────────────

def build_demo() -> str:
    """Render the dashboard from the demo fixture, in a scratch data dir."""
    sys.path.insert(0, str(ENGINE))
    import analyze, demo, insights, normalize, pricing, render  # noqa: E402

    data = OUT / ".scratch"
    if data.exists():
        shutil.rmtree(data)
    data.mkdir(parents=True)

    normalize.write_events(data, demo.generate())
    prices = pricing.load_pricing()
    digest = analyze.build_digest(normalize.read_events(data), prices)
    digest["findings"] = insights.generate(digest, prices)
    # The published demo is deliberately USD/UTC+8 with no plan configured, so
    # it shows the shape of the product rather than one person's settings.
    digest["settings"] = {
        "tz_offset_hours": 8, "tz_label": "UTC+8", "currency": "USD",
        "symbol": "$", "per_usd": 1, "decimals": 2, "plan": "none",
    }
    # `home` is what puts a breadcrumb back to the landing page on the hosted
    # copy. A locally rendered dashboard passes nothing and links to the repo
    # instead, because there is no site to go back to.
    # The demo says what it is on every visit, and its call to action is the
    # first real command rather than a link to a link. Someone who reaches the
    # demo has already decided to look; the next click should start the install,
    # not open another page that asks them to decide again.
    html_out = render.render(
        digest, home="../", demo=True, setup="../setup/", star=REPO,
        refresh="uvx ai-observatory sync digest report")
    shutil.rmtree(data)
    return html_out


def check_locale_tables() -> None:
    """The landing page and the dashboard keep separate locale tables.

    They have to: one is Python that runs at build time, the other is JavaScript
    that runs in a browser opened from `file://`. But two lists that can
    disagree eventually will — a locale added to one and not the other gives a
    switcher entry that 404s, and only a reader who needs that language would
    ever find it. So they are compared here, on every build.
    """
    js = (ENGINE / "assets" / "i18n.js").read_text(encoding="utf-8")
    block = js[js.index("var LOCALES = ["):js.index("];", js.index("var LOCALES = ["))]
    found = re.findall(r'\[\s*"([^"]*)"\s*,\s*"[^"]*"\s*,\s*"[^"]*"\s*,\s*"([^"]*)"\s*\]',
                       block)
    want = [(code, d) for code, d, *_ in i18n.LOCALES]
    if found != want:
        raise SystemExit(
            "build: site/i18n.py and observatory/assets/i18n.js disagree about "
            f"locales.\n  python: {want}\n  js:     {found}")


def sitemap() -> str:
    rows = []
    for _code, d, *_ in i18n.LOCALES:
        rows.append(f"  <url><loc>{SITE}/{d}/</loc></url>" if d
                    else f"  <url><loc>{SITE}/</loc></url>")
    rows.append(f"  <url><loc>{SITE}/demo/</loc></url>")
    rows.append(f"  <url><loc>{SITE}/setup/</loc></url>")
    body = "\n".join(rows)
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
            f"{body}\n</urlset>\n")


def main() -> int:
    if OUT.exists():
        shutil.rmtree(OUT)
    (OUT / "demo").mkdir(parents=True)

    check_locale_tables()

    template = (HERE / "index.html").read_text(encoding="utf-8")
    js = (HERE / "app.js").read_text(encoding="utf-8")
    # Tokens first, then layout — the same order every surface uses, so the
    # landing page and the dashboard cannot drift apart.
    css = ((ENGINE / "assets" / "tokens.css").read_text(encoding="utf-8")
           + "\n" + (HERE / "style.css").read_text(encoding="utf-8"))

    if "/*CSS*/" not in template or "/*JS*/" not in template:
        print("build: index.html is missing a /*CSS*/ or /*JS*/ placeholder",
              file=sys.stderr)
        return 1

    for code, d, *_ in i18n.LOCALES:
        page = render_landing(code, template, css, js)
        target = OUT / d / "index.html" if d else OUT / "index.html"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(page, encoding="utf-8")

    setup_tpl = (HERE / "setup.html").read_text(encoding="utf-8")
    setup_js = (HERE / "setup.js").read_text(encoding="utf-8")
    (OUT / "setup").mkdir(parents=True, exist_ok=True)
    (OUT / "setup" / "index.html").write_text(
        render_setup(setup_tpl, css, js, setup_js), encoding="utf-8")

    (OUT / "demo" / "index.html").write_text(build_demo(), encoding="utf-8")
    (OUT / "robots.txt").write_text(ROBOTS, encoding="utf-8")
    (OUT / "sitemap.xml").write_text(sitemap(), encoding="utf-8")

    # Last, because the CSP is a hash of the pages above: every page has to
    # exist before the header that vouches for them can be written.
    (OUT / "_headers").write_text(
        headers_file(inline_script_hashes(OUT)), encoding="utf-8")

    gaps = i18n.missing()
    if gaps:
        # Not a failure. A locale with a few English lines still beats no locale,
        # and naming them here is what turns "someday" into a reviewable diff.
        print("site: falling back to English for some keys —")
        for code, keys in gaps.items():
            print(f"  {code}: {', '.join(keys)}")

    total = 0
    for path in sorted(OUT.rglob("*")):
        if path.is_file():
            size = path.stat().st_size
            total += size
            print(f"  {path.relative_to(OUT)}  {size / 1024:.0f} KB")
    print(f"site: {len(i18n.LOCALES)} locales, {total / 1024:.0f} KB into "
          f"{OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
