#!/usr/bin/env python3
"""Render the translated READMEs from the site's own copy.

    python3 site/tools/readmes.py        # -> docs/readme/README.<code>.md

Twelve translated READMEs, generated rather than hand-written, from exactly the
strings the website uses (`site/i18n.py`). That is the point: a hand-maintained
translation of a README is a promise nobody keeps — the English changes, the
other twelve rot, and a reader in Jakarta ends up with last year's pitch. Here
there is one place to edit a sentence, and thirteen surfaces update together.

What these pages deliberately do NOT include: the configuration reference, the
command table, and the contributing guide. Those change fast and are full of
file paths and flags; a stale translation of a command is worse than an English
one. Each page links out to the English README for them, and says so.

English is not generated — README.md at the repo root is written by hand,
because it is the canonical document these are derived from.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SITE = ROOT / "site"
OUT = ROOT / "docs" / "readme"
REPO = "https://github.com/jxxyx-bloop/ai-observatory"
HOST = "https://aiobservatory.dev"

sys.path.insert(0, str(SITE))
import i18n  # noqa: E402


def lang_row(current: str) -> str:
    """Every language, with the current one plain rather than linked."""
    out = []
    for code, d, native, _short, _hl in i18n.LOCALES:
        if code == current:
            out.append(f"<b>{native}</b>")
        elif code == "en":
            out.append(f'<a href="../../README.md">{native}</a>')
        else:
            out.append(f'<a href="README.{code}.md">{native}</a>')
    return " ·\n".join(out)


def page(code: str) -> str:
    t = i18n.strings(code)
    site = f"{HOST}/" if code == "en" else f"{HOST}/{dict((c, d) for c, d, *_ in i18n.LOCALES)[code]}/"
    headline = f"{t['hero_h1_a']} {t['hero_h1_b']}{t['hero_h1_c']}".strip()

    return f"""<!-- Generated by site/tools/readmes.py from site/i18n.py. Do not edit by hand:
     edit the strings there and re-run, or the next build will overwrite this. -->

<div align="center">

<img src="../assets/mark.svg" width="72" height="72" alt="">

# AI&nbsp;Observatory

**{headline}**

{t['hero_lede']}

`{t['chip1']}` · `{t['chip2']}` · `{t['chip3']}`

**[{t['cta_demo']}]({HOST}/demo/)** · [{t['brand']}]({site}) · [GitHub]({REPO})

<sub>
{lang_row(code)}
</sub>

<br>

<a href="{HOST}/demo/">
<img src="../assets/demo-light.png#gh-light-mode-only" alt="">
<img src="../assets/demo-dark.png#gh-dark-mode-only" alt="">
</a>

</div>

---

## {t['find_h2']}

> **{t['sev_high']}** — {t['f1_title']} · **{t['f1_save']}**<br>
> {t['f1_body']}<br>
> → {t['f1_act']}

> **{t['sev_med']}** — {t['f2_title']} · **{t['f2_save']}**<br>
> {t['f2_body']}<br>
> → {t['f2_act']}

> **{t['sev_low']}** — {t['f3_title']} · **{t['f3_save']}**<br>
> {t['f3_body']}<br>
> → {t['f3_act']}

{t['find_note']}

## {t['rm_quick']}

```bash
git clone {REPO}
cd ai-observatory/observatory
python3 observe.py demo digest report
```

{t['rm_own']}

```bash
python3 observe.py demo --purge
python3 observe.py all
```

{t['run_note']}

## {t['how_h2']}

| | | |
|---|---|---|
| **01 {t['how_1_t']}** | **02 {t['how_2_t']}** | **03 {t['how_3_t']}** |
| {t['how_1_d']} | {t['how_2_d']} | {t['how_3_d']} |

{t['how_note']}

<picture>
  <source media="(prefers-color-scheme: dark)" srcset="../assets/peak-clock-dark.svg">
  <img src="../assets/peak-clock-light.svg" alt="">
</picture>

## {t['why_h2']}

| | |
|---|---|
| **{t['why_1_t']}** | {t['why_1_d']} |
| **{t['why_2_t']}** | {t['why_2_d']} |
| **{t['why_3_t']}** | {t['why_3_d']} |
| **{t['why_4_t']}** | {t['why_4_d']} |

## {t['priv_h2']}

**{t['priv_lede']}**

- {t['priv_1']}
- {t['priv_2']}
- {t['priv_3']}

## {t['foot_docs']}

{t['rm_docs_en']}

- [README]({REPO}#quick-start)
- [{t['foot_limits']}]({REPO}/blob/main/docs/context/Known-Limitations.md)
- [{t['foot_contrib']}]({REPO}/blob/main/CONTRIBUTING.md)

{t['rm_translate']}

---

<sub>{t['foot_tag']} · {t['rm_generated']}</sub>
"""


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    written = 0
    for code, *_ in i18n.LOCALES:
        if code == "en":
            continue                      # README.md is the hand-written source
        path = OUT / f"README.{code}.md"
        path.write_text(page(code), encoding="utf-8")
        print(f"  {path.relative_to(ROOT)}")
        written += 1
    print(f"readmes: {written} translated READMEs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
